stages:
  load:
    cmd: python src/load.py
    deps:
      - src/load.py
      - data/raw/motor_current_signals.pkl
      - src/utils/data/load.py
      - src/utils/data/write.py
    params:
      - load.decimation_factor
      - load.moving_average_win_size
    outs:
      - data/interim/processed_signal.pkl
  decompose:  
    cmd: python src/decompose.py 
    deps:
      - src/decompose.py
      - data/interim/processed_signal.pkl
      - src/utils/models/trend.py
      - src/utils/models/seasonality.py
      - src/utils/decomposition/decomposition.py
      - src/utils/data/write.py
    outs:
      - data/decomposed/trend.pkl
      - data/decomposed/seasonal_pattern.pkl
      - data/decomposed/residual.pkl
    plots:
      - plots/decomposition.png
      - plots/seasonal_pattern.png
  analyze_decomposition_residuals:  
    cmd: python src/analyze_decomposition_residuals.py
    deps:
      - src/analyze_decomposition_residuals.py
      - src/utils/signals/correlation.py
      - src/utils/visual/correlation.py
      - data/interim/processed_signal.pkl
      - data/decomposed/residual.pkl
    plots:
      - plots/complete_residual_autocorrelation.png
      - plots/residual_autocorrelation.png
  model_residuals:  
    cmd: python src/model_residuals.py
  # analyze_pzp:  
  # analyze_tfr:  
  # detect_anomaly: ? keep this?
