stages:
  load:
    cmd: python src/load.py
    deps:
      - src/load.py
      - data/raw/motor_current_signals.pkl
      - params/load.json
    params:
      - decimation_factor
      - moving_average_win_size
    outs:
      - data/interim/processed_signal.parquet
